apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendation-v2-retry
spec:
  destination:
    namespace: tutorial
    name: recommendation
  precedence: 3
  route:
  - labels:
      version: v2
  httpReqRetries:
    simpleRetry:
      perTryTimeout: 2s
      attempts: 3
