apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendation-delay
spec:
  destination:
    namespace: tutorial
    name: recommendation
  precedence: 2
  route:
  - labels:
      app: recommendation
  httpFault:
    delay:
      percent: 50
      fixedDelay: 7s
